In [2]:
#q1
import numpy as np 


In [3]:
arr=np.random.randint(1,11,size=(3,4))

In [4]:
print(arr)

[[ 1  1  7 10]
 [ 6  2  9  5]
 [ 2  4  5  3]]


In [7]:
maximum_value = np.max(arr)
print(maximum_value)

10


In [8]:
rows_mean=np.mean(arr, axis=1)
print(rows_mean)

[4.75 5.5  3.5 ]


In [10]:
reshape_arr=np.reshape(arr,(2,6))
print(reshape_arr)

[[ 1  1  7 10  6  2]
 [ 9  5  2  4  5  3]]


In [11]:
mul_arr = arr *2 
print(mul_arr)

[[ 2  2 14 20]
 [12  4 18 10]
 [ 4  8 10  6]]


In [15]:
arr=np.arange(10)
odd_numbers = arr[arr%2!=0]
print(arr)
print(odd_numbers)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [16]:
identity_mat=np.identity(3)
print(identity_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
arr =np.random.randn(5,5)
print(arr)
mean=np.mean(arr)
std = np.std(arr)
nor_arr = (arr-mean)/std
print(nor_arr)

[[ 1.44012710e+00 -7.13200006e-01  8.25552710e-01 -1.51591683e+00
  -1.46030261e+00]
 [-2.05084371e-01 -3.94627678e-01 -2.65804646e-01 -8.70999027e-01
  -1.50887997e-02]
 [ 1.27549836e+00 -4.87010121e-01  4.96107976e-01 -1.36804399e-03
  -2.79838034e-01]
 [ 1.57699013e+00  7.50390144e-01 -4.42305914e-01 -9.22479933e-01
  -9.24836616e-01]
 [-8.16815933e-01  5.67856709e-01 -1.26803651e+00  3.50273099e-01
   2.59298532e-02]]
[[ 1.843706   -0.6832081   1.12250731 -1.62519061 -1.55992772]
 [-0.086938   -0.30936573 -0.15819281 -0.86838413  0.13602046]
 [ 1.65051535 -0.41777587  0.73590625  0.15212167 -0.1746609 ]
 [ 2.00431381  1.03430457 -0.3653158  -0.92879661 -0.93156216]
 [-0.80480066  0.82010288 -1.3343048   0.56477006  0.18415555]]


In [19]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[2, 3, 4],
                 [5, 6, 7]])
result = arr1 * arr2
print(result)

[[ 2  6 12]
 [20 30 42]]


In [21]:
heights_cm = np.array([160, 170, 180, 190])
height_inch=heights_cm/2.54
print(height_inch)

[62.99212598 66.92913386 70.86614173 74.80314961]


In [22]:
arr =np.arange(10)
arr[arr%2!=0] =-1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [9]:
arr = np.random.randint(1,11,size=(3,4))

In [10]:
print(arr)

[[1 7 4 4]
 [5 4 9 4]
 [6 7 5 4]]


In [11]:
max_value = np.max(arr)
print(max_value)

9


In [12]:
row_mean = np.mean(arr, axis=1)
print(row_mean)

[4.  5.5 5.5]


In [13]:
arr1=arr.reshape(2,6)
print(arr1)


[[1 7 4 4 5 4]
 [9 4 6 7 5 4]]


In [14]:
print(arr*2)

[[ 2 14  8  8]
 [10  8 18  8]
 [12 14 10  8]]


In [15]:
mat = np.identity(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
narr=np.arange(10)
odd_num = narr[narr%2 !=0]
print(odd_num)

[1 3 5 7 9]


In [27]:
arr1 = np.random.rand(5,5)
mean = np.mean(arr1)
std = np.std(arr1)
normalize= (arr1-mean)/std
print(normalize)

[[ 0.00244262  0.03438306 -1.73493031 -1.42372306  0.32990905]
 [-0.59031079  1.31935489  1.14520487  0.28451547  0.87685051]
 [-0.54188771  0.88709617  0.70062345 -0.2457866   1.40539949]
 [ 1.01059704 -1.19132855  0.09418661  1.05596981 -1.75255199]
 [-1.24108006 -1.74000741  0.18952566  0.81006615  0.31548163]]


In [30]:
a = [[1,2,3],[3,5,6],[7,8,9]]
b =[[9,8,7],[6,5,4],[3,2,1]]
arr1 = np.array(a)
arr2 = np.array(b)
mul= arr1*arr2
print(mul)

[[ 9 16 21]
 [18 25 24]
 [21 16  9]]


In [31]:
heights_cm = np.array([160, 170, 180, 190])
height_inch = heights_cm/2.54
print(height_inch)

[62.99212598 66.92913386 70.86614173 74.80314961]


In [35]:
arr1 = np.arange(10)
print(arr1)
odd_num=arr1[arr1 %2 !=0] 
arr1[odd_num]=-1
print(arr1)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]
