In [1]:
import numpy as np

In [4]:
a=[1,2.0,3]
a_array=np.array(a)
a_array.dtype

dtype('float64')

In [5]:
print(a_array)

[1. 2. 3.]


In [6]:
a_array.ndim

1

In [18]:
a=[[1,2,3],[4,5,6],[7,8,9]]
a_array=np.array(a)
a_array.dtype

dtype('int64')

In [8]:
a_array.ndim

2

In [9]:
print(a_array)

[[1 2 3]
 [4 5 6]]


In [12]:
# acess element in array
print(a_array[0,1])

2


In [14]:
print(a_array[1,-1])

6


In [15]:
print(a_array[1,:])

[4 5 6]


In [19]:
print(a_array[:,1])

[2 5 8]


In [21]:
print(a_array[0:2,1:3])

[[2 3]
 [5 6]]


In [22]:
#assign a value/ change the value 
a_array[2,2]

np.int64(9)

In [23]:
a_array[2,2]=11

In [24]:
a_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 11]])

In [25]:
a_array[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [26]:
a_array[0:2,1:3]=[[11,31],[11,29]]

In [27]:
a_array

array([[ 1, 11, 31],
       [ 4, 11, 29],
       [ 7,  8, 11]])

In [30]:
a=[[[1,2],[3,4]],[[5,6],[7,8]]]
a_array=np.array(a)

In [31]:
a_array

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [32]:
a_array[0,0,0]

np.int64(1)

In [35]:
a_array[1,1,1]

np.int64(8)

In [38]:
#initializee the array
a_array=np.zeros(5)

In [39]:
a_array

array([0., 0., 0., 0., 0.])

In [40]:
#initializee the array
a_array=np.zeros(5,dtype='int64')

In [41]:
a_array

array([0, 0, 0, 0, 0])

In [44]:
a_array=np.zeros((2,3),dtype='int64')
a_array

array([[0, 0, 0],
       [0, 0, 0]])

In [45]:
a_array=np.ones((2,3),dtype='int64')
a_array

array([[1, 1, 1],
       [1, 1, 1]])

In [46]:
a_array=np.full((2,3),11)
a_array

array([[11, 11, 11],
       [11, 11, 11]])

In [47]:
#array od random decimal values
a_array=np.random.rand(2,3)
a_array

array([[0.9134426 , 0.77554744, 0.97122505],
       [0.0699931 , 0.04365437, 0.3850364 ]])

In [48]:
#array of identitiy matrix


In [50]:
#array of identitiy matrix
a_array=np.identity(3,dtype='int64')
a_array

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [55]:
a_array=np.identity(3,dtype='int64')
a_array1=a_array
a_array[0,0]=11
a_array
a_array1

array([[11,  0,  0],
       [ 0,  1,  0],
       [ 0,  0,  1]])

In [56]:
#For copying yhe list or array we must have to use the copy function because in python it referer the same adress 
a_array=np.identity(3,dtype='int64')
a_array1=a_array.copy()
a_array[0,0]=11
a_array
a_array1

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [57]:
a_array

array([[11,  0,  0],
       [ 0,  1,  0],
       [ 0,  0,  1]])

In [63]:
add=a_array+2
add

array([[13,  2,  2],
       [ 2,  3,  2],
       [ 2,  2,  3]])

In [59]:
a_array*2

array([[22,  0,  0],
       [ 0,  2,  0],
       [ 0,  0,  2]])

In [64]:
add*2

array([[26,  4,  4],
       [ 4,  6,  4],
       [ 4,  4,  6]])

In [67]:
a_array1=np.full((2,3),9,dtype='int64')
a_array2=np.full((2,3),5,dtype='int64')

In [68]:
a_array1

array([[9, 9, 9],
       [9, 9, 9]])

In [69]:
a_array2

array([[5, 5, 5],
       [5, 5, 5]])

In [66]:
a_array1+a_array2

array([[14, 14, 14],
       [14, 14, 14]])

In [70]:
a_array1*a_array2

array([[45, 45, 45],
       [45, 45, 45]])

In [72]:
#statistics
a=[[1,2,3],[4,5,6],[7,8,9]]
a_array=np.array(a)
a_array.dtype

dtype('int64')

In [73]:
a_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
print(np.min(a_array))
print(np.max(a_array))
print(np.mean(a_array))
print(np.median(a_array))


1
9
5.0
5.0


In [79]:
np.min(a_array,axis=0)

array([1, 2, 3])

In [80]:
np.min(a_array,axis=1)

array([1, 4, 7])

In [81]:
np.sum(a_array)

np.int64(45)

In [82]:
np.sum(a_array,axis=0)

array([12, 15, 18])

In [83]:
np.sum(a_array,axis=1)

array([ 6, 15, 24])

In [84]:
#rearrange the array
a=[[1,2,3],[4,5,6],[7,8,9]]
a_array=np.array(a)
a_array.dtype

dtype('int64')

In [85]:
a_array.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [86]:
a_array1=np.full((2,3),9,dtype='int64')
a_array2=np.full((2,3),5,dtype='int64')
print(a_array1)
print(a_array2)

[[9 9 9]
 [9 9 9]]
[[5 5 5]
 [5 5 5]]


In [88]:
#stacking multiple arrays 
#vstack is for vertical stacking
np.vstack((a_array1,a_array2))

array([[9, 9, 9],
       [9, 9, 9],
       [5, 5, 5],
       [5, 5, 5]])

In [89]:
#hstack is for horizontal stacking
np.hstack((a_array1,a_array2))

array([[9, 9, 9, 5, 5, 5],
       [9, 9, 9, 5, 5, 5]])

In [96]:
#create array from file 
f=np.genfromtxt(r'C:\Users\sudha\Desktop\Python\Ankit_Bansal\readnp.txt',delimiter=',',dtype='int64')

In [97]:
f

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [98]:
#advance indexing
f<10

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False, False, False]])

In [99]:
#give only the element

In [101]:
f[f<10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
f[(f>5) &(f<10)]

array([6, 7, 8, 9])

In [104]:
f[(f>5) |(f<10)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])